import Head from "next/head";

import Navbar from "../components/Navbar";
import Card from "./Card";
import { Inter } from "@next/font/google";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>
          MultiPay - Transfer from Any chain to Any chain, Any coin to Any coin.
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <div className="min-h-screen">
          <div className="relative">
            <Navbar />
          </div>

          <Card />
        </div>
      </main>
    </>
  );
}
